### ISSUE TITLE
Axis is not copied into MDBM_Problem

### ISSUE THREAD

**Issue by HTSykora** [bachrathyd/MDBM.jl#12]
```julia
using MDBM

a=Axis(-1:1)
prob=MDBM_Problem((x,y)->x-y,[a,a])

solve!(prob,1)

a #== [-1,-0.75,-0.5,-0.25,0.,0.25, ... ,1] instead of [-1,0,1]
```

**Comment by HTSykora** [comment]
Resolved in 14afaf1addc8c6a6ab7fd86e0a5bfac36e4a62d0

**Comment by bachrathyd** [comment]
Azt eddig tudtam, hogy az eredetileg adott tengely módusol, de úgy voltam
vele, hogy "feature" és nem "bug" :-D
de ilyen meghívásra nem is gondoltam, így tényleg rossz lett volna!
Kösz a javítást!
Van vele bármi tennivalóm?
Dani

Dr. Daniel Bachrathy
assistant professor
Budapest University of Technology and Economics
Department of Applied Mechanics
bachrathy@mm.bme.hu
